name: Release
on: [release, workflow_dispatch]
env:
    OUTPUT_DIRECTORY = ./docs
    INPUT = ./
    HTML_OUTPUT = ./docs
jobs:
    doxygenize:
        name: Generate Doxygen documentation
        runs-on: ubuntu-latest
        steps:
        - name: Doxygenize
          uses: langroodi/doxygenize@v1.7.0
