name: Release
on: [release, workflow_dispatch]
jobs:
    doxygenize:
        name: Generate Doxygen documentation
        runs-on: master
        steps:
        - name: Doxygenize
          uses: langroodi/doxygenize@v1.7.0
