name: Release
on: [release, workflow_dispatch]
jobs:
    doxygenize:
        name: Generate Doxygen documentation
        runs-on: ubuntu-latest
        steps:
        - run: |
            ls .
        - name: Doxygenize
          uses: langroodi/doxygenize@v1.7.0
          with:
              doxygenconf: './docs/Doxyfile'